export default {
    color: {
        red: 'w3-red',
        pink: 'w3-pink',
        purple: 'w3-purple',
        deepPurple: 'w3-deep-purple',
        indigo: 'w3-indigo',
        blue: 'w3-blue',
        lightBlue: 'w3-light-blue',
        cyan: 'w3-cyan',
        aqua: 'w3-aqua',
        teal: 'w3-teal',
        green: 'w3-green',
        lightGreen: 'w3-light-green',
        lime: 'w3-lime',
        sand: 'w3-sand',
        khaki: 'w3-khaki',
        yellow: 'w3-yellow',
        amber: 'w3-amber',
        orange: 'w3-orange',
        deepOrange: 'w3-deep-orange',
        blueGray: 'w3-blue-gray',
        brown: 'w3-brown',
        lightGray: 'w3-light-gray',
        gray: 'w3-gray',
        darkGray: 'w3-dark-gray',
        black: 'w3-black',
        paleRed: 'w3-pale-red',
        paleYellow: 'w3-pale-yellow',
        paleGreen: 'w3-pale-green',
        paleBlue: 'w3-pale-blue'
    },
    fontSize: {
        tiny: 'w3-tiny',
        small: 'w3-small',
        medium: 'w3-medium',
        large: 'w3-large',
        xLarge: 'w3-xlarge',
        xxLarge: 'w3-xxlarge',
        xxxLarge: 'w3-xxxlarge',
        jumbo: 'w3-jumbo'
    }
}